export default {
  user: {
    add: '/user',
    login: '/user/login',
    telLogin: '/user/tel-login',
    checkToken: '/user/check-token',
    refreshToken: '/user/refresh-token',
    query: '/user',
    update: '/user',
    resetPassword: '/user/resetPassword',
    sendEmailCaptcha: '/user/sendEmailCaptcha',
    sendSmsCaptcha: '/user/sendSmsCaptcha',
    checkCaptcha: '/user/checkCaptcha',
    checkUser: '/user/checkUser',
  },
  device: {
    add: '/device',
    query: '/device',
    update: '/device',
    delete: '/device',
    export: '/device/export',
  },
  agent: {
    add: '/agent',
    query: '/agent',
    update: '/agent',
    delete: '/agent',
  },
  role: {
    add: '/role',
    query: '/role',
    update: '/role',
    delete: '/role',
    testVoice: '/role/testVoice',
    sherpaVoices: '/role/sherpaVoices',
  },
  template: {
    query: '/template',
    add: '/template',
    update: '/template',
    delete: '/template',
  },
  message: {
    query: '/message',
    update: '/message',
    delete: '/message',
    export: '/message/export',
  },
  config: {
    add: '/config',
    query: '/config',
    update: '/config',
  },
  mcpTool: {
    toggleStatus: '/mcpTool/toggleStatus',
    toggleGlobalStatus: '/mcpTool/toggleGlobalStatus',
    batchSetExcludeTools: '/mcpTool/batchSetExcludeTools',
    getDisabledTools: '/mcpTool/getDisabledTools',
    getSystemGlobalTools: '/mcpTool/getSystemGlobalTools',
    refreshCache: '/mcpTool/refreshCache',
  },
  firmware: {
    query: '/firmware',
    upload: '/firmware/upload',
    update: '/firmware',
    delete: '/firmware',
    setDefault: '/firmware',
  },
  voiceClone: {
    upload: '/voice-clone/upload',
    list: '/voice-clone/list',
    delete: '/voice-clone',
    preview: '/voice-clone/preview',
  },
  upload: '/file/upload',
  memory: {
    summary: '/memory/summary',
    long: '/memory/long',
  },
  monitor: {
    dailyUsage: '/monitor/usage/daily',
    summary: '/monitor/usage/summary',
    activeDevices: '/monitor/active-devices',
    latency: '/monitor/latency',
  },
  knowledge: {
    baseQuery: '/knowledge/base',
    baseAdd: '/knowledge/base',
    baseUpdate: '/knowledge/base',
    baseDelete: '/knowledge/base',
    docQuery: '/knowledge/doc',
    docUpload: '/knowledge/doc/upload',
    docDelete: '/knowledge/doc',
    docReprocess: '/knowledge/doc',
    docStatus: '/knowledge/doc',
  },
}




